### ISSUE TITLE
Steering Control stalls on round 0

### ISSUE THREAD

**Issue by tneale-gt** [RiS3-Lab/p2im#22]
I built the Steering_Control example firmware using thre command in   README.md (although I had to install the needed arduino packages first):

```
# cd REPO/externals/p2im-real_firmware/Steering_Control
# ../deps/arduino-cli core install arduino:sam
# ../deps/arduino-cli lib install Servo
# ../deps/arduino-cli/arduino-cli compile -b arduino:sam:arduino_due_x_dbg *.ino --build-path `realpath ./build` -o firmware
```

Then created a fuzzing directory for the firmware.elf, and edited fuzz.cfg. When I run fuzz.py, qemu apparently hangs:

```
root@p2im:/workspace/fuzzing/Steering_Control/2# /root/p2im/model_instantiation/fuzz.py -c fuzz.cfg 
Change working dir to: /workspace/fuzzing/Steering_Control/2
CWD: /workspace/fuzzing/Steering_Control/2

try our best to extract model w/o input
cmd_me0: /root/p2im/model_instantiation/me.py -c /workspace/fuzzing/Steering_Control/2/fuzz.cfg --run-num 0 --print-to-file

Change working dir to: 0/
CWD: /workspace/fuzzing/Steering_Control/2/0
Redirect stdout to file named stdout

extract model for each seed input
0.random.1
run f/w w/ seed input to check if there is aup
cmd_qemu: /root/p2im/qemu/precompiled_bin/qemu-system-gnuarmeclipse -nographic -aflFile /workspace/fuzzing/Steering_Control/2/inputs/random -board Arduino-Due -mcu SAM3X8E -image /workspace/fuzzing/Steering_Control/2/firmware.elf -pm-stage 3 -model-input /workspace/fuzzing/Steering_Control/2/0/peripheral_model.json -me-bin /root/p2im/model_instantiation/me.py -me-config /workspace/fuzzing/Steering_Control/2/fuzz.cfg

qemu hangs(pid: 32343). seed input should not hang!
No aup, don't run ME

launch fuzzer
cmd_afl: /root/p2im/afl/afl-fuzz -i /workspace/fuzzing/Steering_Control/2/inputs -o /workspace/fuzzing/Steering_Control/2/outputs -t 150+ -QQ -a /root/p2im/model_instantiation/me.py -b /workspace/fuzzing/Steering_Control/2/fuzz.cfg -c /workspace/fuzzing/Steering_Control/2/0/peripheral_model.json -T Steering_Control_2 -d /root/p2im/qemu/precompiled_bin/qemu-system-gnuarmeclipse -nographic -board Arduino-Due -mcu SAM3X8E -image /workspace/fuzzing/Steering_Control/2/firmware.elf -pm-stage 3 -aflFile @@

afl-fuzz 2.06b by <lcamtuf@google.com>
[+] You have 2 CPU cores and 3 runnable tasks (utilization: 150%).
[*] Checking core_pattern...
[*] Setting up output directories...
[*] Scanning '/workspace/fuzzing/Steering_Control/2/inputs'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:random'...
[!] WARNING: Test case results in a hang (skipping)

[-] PROGRAM ABORT : All test cases time out, giving up!
         Location : perform_dry_run(), afl-fuzz.c:2812
```

Using the run_fw.py script to attach a debugger, I see that code is looping in the delay() function, repeateadly calling GetTickCount() but the result is always 0, so delay never returns. 

Is there a way to turn on the timer emulation, or should it be driven by an interrupt?

I'm using a Ubuntu 16.04 docker image, gcc-arm-none-eabi-10.3.2021 (objdump 2.36.1.20210621), and the precompiled qemu.

**Comment by alejoseb** [comment]
You can change the code to increase the counter every time the get tick function is called. That is a hack but probably enough for testing the rest of the code.

**Comment by tneale-gt** [comment]
OK, I modified ~/.arduino15/packages/arduino/hardware/sam/1.6.12/cores/arduino/wiring.c so that references to GetTickCount() are replaced by a function returning a number that increments each time it is called. The emulation no longer stalls in delay(), but it still stalls. The problem seems to be caused by an infinite loop in the function UDD_InitEP()

```
    0x82270 <UDD_InitEP+32>         lsls    r3, r3, #13 
    0x82272 <UDD_InitEP+34>         bmi.n   0x82276 <UDD_InitEP+38>
   >0x82274 <UDD_InitEP+36>         b.n     0x82274 <UDD_InitEP+36>
    0x82276 <UDD_InitEP+38>         bx      lr
    0x82278 <UDD_InitEP+40>         andmi   r12, r10, r0
----------------------------------------------------------------------------------
(gdb) stepi
0x00082274 in UDD_InitEP ()
0x00082274 in UDD_InitEP ()
0x00082274 in UDD_InitEP ()
(gdb) bt
#0  0x00082274 in UDD_InitEP ()
#1  0x00081a3c in USB_ISR () at /root/.arduino15/packages/arduino/hardware/sam/1.6.12/cores/arduino/USB/USBCore.cpp:614
#2  0x00080dae in UOTGHS_Handler ()
#3  0xfffffff8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)        
```

I avoided that by modifying 
~/.arduino15/packages/arduino/hardware/sam/1.6.12/cores/arduino/USB/USBCore.cpp
to make the USB_ISR() function always return without doing anything. Now I can proceed to run the fuzzer.

Is that an expected modification, or is there a better alternative (or am I doing something wrong?). Thanks for your help.
